plugins {
    id 'java'
    id 'checkstyle'
}

repositories {
    mavenLocal()
    maven {
        url = 'https://repo.runelite.net'
        content {
            excludeGroup 'org.lwjgl'
        }
    }
    mavenCentral()
}

def runeLiteVersion = 'latest.release'
def lwjglVersion = '3.3.2'
def lwjglNatives = 'natives-windows'

dependencies {
    compileOnly group: 'net.runelite', name: 'client', version: runeLiteVersion
    compileOnly 'org.projectlombok:lombok:1.18.30'
    annotationProcessor 'org.projectlombok:lombok:1.18.30'

    testImplementation(group: 'net.runelite', name: 'client', version: runeLiteVersion) {
        exclude group: 'org.lwjgl'
    }
    testImplementation(group: 'net.runelite', name: 'jshell', version: runeLiteVersion) {
        exclude group: 'org.lwjgl'
    }

    // Base jars (classes) + windows natives
    testImplementation "org.lwjgl:lwjgl:$lwjglVersion"
    testImplementation "org.lwjgl:lwjgl-opengl:$lwjglVersion"
    testImplementation "org.lwjgl:lwjgl-openal:$lwjglVersion"
    testImplementation "org.lwjgl:lwjgl-glfw:$lwjglVersion"
    testImplementation "org.lwjgl:lwjgl-stb:$lwjglVersion"
    testImplementation "org.lwjgl:lwjgl-tinyfd:$lwjglVersion"

    testRuntimeOnly "org.lwjgl:lwjgl:$lwjglVersion:$lwjglNatives"
    testRuntimeOnly "org.lwjgl:lwjgl-opengl:$lwjglVersion:$lwjglNatives"
    testRuntimeOnly "org.lwjgl:lwjgl-openal:$lwjglVersion:$lwjglNatives"
    testRuntimeOnly "org.lwjgl:lwjgl-glfw:$lwjglVersion:$lwjglNatives"
    testRuntimeOnly "org.lwjgl:lwjgl-stb:$lwjglVersion:$lwjglNatives"
    testRuntimeOnly "org.lwjgl:lwjgl-tinyfd:$lwjglVersion:$lwjglNatives"

    testImplementation 'junit:junit:4.12'
    testImplementation 'org.mockito:mockito-core:3.12.4'
    testAnnotationProcessor 'org.projectlombok:lombok:1.18.30'
}

group = 'gg.veil'
version = '3.0.0'

java {
    sourceCompatibility = JavaVersion.VERSION_11
    targetCompatibility = JavaVersion.VERSION_11
}

tasks.withType(JavaCompile) {
    options.encoding = 'UTF-8'
}
