displayName=Veil Flipper
description=Tracks your GE offers in real-time and syncs live data to the Veil mobile app. Auto-logs completed trades, calculates profit/loss, and serves a local API for Veil.
tags=ge,grand exchange,flip,flipper,merch,merchant,profit,veil,mobile
plugins=gg.veil.veilplugin.VeilPlugin
support=https://github.com/MisTAiM/veil-rl-plugin
